config/routes.rb
Rails.application.routes.draw do
  resources :inventory_systems

  # get "inventory_systems/home" => "inventory_systems#home"
  get "inventory_systems/home" => "inventory_systems#home"
  root 'inventory_systems#index'
  # get "inventory_systems/next" => "inventory_systems#next"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#home"
  # get "welcome/say_monday" => "welcome#monday"
  # get "welcome/tuesday" => "welcome#tueday"
  # get "welcome/wednesday" => "welcome#wednesday"
  # get "welcome/thursday" => "welcome#thursday"
  # get "welcome/friday" => "welcome#friday"
  # get "welcome/home" => "welcome#home"

  # get "posts/new" => "posts#new"
  # get "posts/home" => "posts#home"
  resources :posts

  # ...
  # root 'welcome#home'
  # ...
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/inventory_system.rb
class InventorySystem < ApplicationRecord
  validates :product_name, presence: true
  validates :product_type, presence: true
  validates :product_quantity, presence: true
  validates :product_description, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  # validates :posts, product_name: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/inventory_systems_controller.rb
class InventorySystemsController < ApplicationController
  before_action :set_inventory_system, only: [:show, :edit, :update, :destroy]

  def index
    @inventory_systems = InventorySystem.all
  end

  def new
    @inventory_system = InventorySystem.new
  end

  def create
    @inventory_system = InventorySystem.new(inventory_system_params)
    if @inventory_system.save
      redirect_to inventory_systems_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end



  def update
    if @inventory_system.update(inventory_system_params)
      redirect_to inventory_systems_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @inventory_system.destroy
    redirect_to inventory_systems_path
  end

  def home
  end
  private
end

  def set_inventory_system
    @inventory_system = InventorySystem.find(params[:id])
  end

  def inventory_system_params
    params.require(:inventory_system).permit(:product_name, :product_type, :product_quantity, :product_description)
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_inventory_system, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params[:post].permit(:product_name, :product_id, :product_quantity, :product_description, :product_availability))
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def show
  end

  # def edit
  #   @post = Post.find(params[:id])
  # end

  def update
    @post = Post.find(params[:id])
    @post.update(params.require(:post).permit())
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    link_to posts_path
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def post_param

  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def say

  end
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventory_systems_helper.rb
module InventorySystemsHelper
end

app/helpers/my_project_helper.rb
module MyProjectHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/inventory_systems/_footer.html.erb
<footer class="position-sticky text-white-50">
  <p>Creator: <a href="#" class="text-white">Mark Carlo V. Garjas</a> @2022 <a href="https://facebook.com/carlogarjas" class="text-white">@carlogarjas</a>.</p>
</footer>

app/views/inventory_systems/_form.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body class="text-center pt-4 bg-dark" style="">
  <div class="container pt-2" style="height: 700px">
    <%= form_with model: @inventory_system do |form| %>
      <div class="form-group row justify-content-center align-content-center pt-3">
        <% form.label :product_name,for:'inputEmail3', class: 'col-lg-2 col-form-label'%>
        <div class="col-lg-3">
            <%= form.text_field :product_name, class: 'form-control',placeholder: 'Product Name'%>
        </div>
      </div>

      <div class="form-group row justify-content-center align-content-center pt-3">
        <% form.label :product_type, class: 'col-lg-2 col-form-label'%>
        <div class="col-lg-3">
          <%= form.text_field :product_type, class: 'form-control',placeholder: 'Product Type'%>
        </div>
      </div>

      <div class="form-group row justify-content-center align-content-center pt-3">
        <% form.label :product_quantity, class: 'col-lg-2 col-form-label'%>
        <div class="col-lg-3">
          <%= form.number_field :product_quantity, class: 'form-control',placeholder: 'Product Quantity'%>
        </div>
      </div>

      <div class="form-group row justify-content-center align-content-center pt-3">
        <% form.label :product_description, class: 'col-lg-2 col-form-label'%>
        <div class="col-lg-3">
          <%= form.text_area :product_description, class: 'form-control',placeholder: 'Product Description'%>
        </div>
      </div>

      <%= form.submit value: 'Add Product',class: 'mt-3 btn btn-warning'%>
      <% if @inventory_system.errors.any? %>
        <ul>
          <% @inventory_system.errors.each do |error| %>
            <ol class><%= error.full_message %></ol>
          <% end %>
        </ul>
      <% end %>
      <% end %>
    <p class="mt-4"><%= link_to 'Back to Dashboard', inventory_systems_path, class: 'nav-link'%></p>
  </div>
</body>
</html>

app/views/inventory_systems/_header.html.erb
<div class="container">
  <header class="d-flex justify-content-center mb-5">
    <ul class="nav nav-pills">
      <li class="nav-item"> <%= link_to 'Home', inventory_systems_home_path, class: 'nav-link'%></li>
      <li class="nav-item"> <%= link_to 'Dashboard', inventory_systems_path, class: 'nav-link'%></li>
      <li class="nav-item"> <%= link_to 'Add Product', new_inventory_system_path, class: 'nav-link'%></li>

    </ul>
  </header>
</div>

app/views/inventory_systems/_home.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body class="text-center pt-4 bg-dark">
<div class="container pt-2">
  <main class="px-3 mt-5" style="height: 660px">
    <h1>Online Inventory System.</h1>
    <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet animi eius facilis fuga numquam! A adipisci aperiam deserunt, dolorum earum ipsam labore necessitatibus, non omnis tempora tempore vero vitae, voluptatum.</p>
    <p class="lead">
      <a href="#" class="btn btn-lg btn-secondary mt-5 fw-bold border-white bg-black">Learn more</a>
    </p>
  </main>
</div>
</body>
</html>

app/views/inventory_systems/_index.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body class="text-center pt-4 bg-dark">
<div class="container py-2" style="height: 700px;">

  <table class="table table-bordered border-secondary text-light">
    <thead class="">
    <tr class="">
      <td class="">ID</td>
      <td class="">Product Name</td>
<!--      <td class="border border-2 border-light">Product Type</td>-->
<!--      <td class="border border-2 border-light">Product Quantity</td>-->
<!--      <td class="border border-2 border-light">Product Description</td>-->
      <td class=""></td>
      <td class=""></td>
    </tr>
    </thead>
    <% @inventory_systems.each do |inventory_system| %>
      <tr class="">
        <td class=""><p class="text-lg-center"><%= inventory_system.id%></p> </td>
        <td class=""><p class="text-lg-center"><%= inventory_system.product_name%></p> </td>
<!--        <td class="border border-2 border-light"><p class="text-lg-center"><%#= inventory_system.product_type %></p></td>-->
<!--        <td class="border border-2 border-light"><p class="text-lg-center"><%#= inventory_system.product_quantity %></p></td>-->
<!--        <td class="border border-2 border-light"><p class="text-lg-center"><%#= inventory_system.product_description %></p></td>-->
        <td><p class="text-lg-center"><%= link_to 'Show', inventory_system_path(inventory_system), class: 'text-light' %> | <%= link_to 'Edit', edit_inventory_system_path(inventory_system), class: 'text-light'%></p></td>
        <td><%= button_to 'Delete', inventory_system_path(inventory_system), class: 'btn btn-sm', method: :delete %></td>
      </tr>
    <% end %>
  </table>

</div>
</body>
</html>

app/views/inventory_systems/_show.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body class="text-center pt-4 bg-dark" style="">
<div class="container pt-2" style="height: 700px">
  <p>Product Type: <%= @inventory_system.product_type %></p>
  <p>Product Quantity: <%= @inventory_system.product_quantity %></p>
  <p>Product Description: <%= @inventory_system.product_description %></p>

  <p class="mt-4"><%= link_to 'Back to Dashboard', inventory_systems_path, class: 'nav-link'%></p>
</div>

</body>
</html>

app/views/inventory_systems/edit.html.erb
<%= render partial: 'header', locals: { inventory_system: @inventory_system } %>
<h1 class="text-light text-center">| Edit <%= @inventory_system.product_name %> |</h1>
<%= render "form", inventory_system: @inventory_system %>

<%= render partial: 'footer', locals: { inventory_system: @inventory_system } %>

app/views/inventory_systems/home.html.erb
<%= render partial: 'header', locals: { inventory_system: @inventory_system } %>
<h1 class="text-light text-center">Dashboard | Inventory System</h1>
<%= render partial: 'index', locals: { inventory_system: @inventory_system } %>
<%= render partial: 'footer', locals: { inventory_system: @inventory_system } %>

app/views/inventory_systems/index.html.erb
<%= render partial: 'header', locals: { inventory_system: @inventory_system } %>
<h1 class="text-light text-center">Dashboard | Inventory System</h1>
<%= render partial: 'index', locals: { inventory_system: @inventory_system } %>
<%= render partial: 'footer', locals: { inventory_system: @inventory_system } %>

app/views/inventory_systems/new.html.erb
<%= render partial: 'header', locals: { inventory_system: @inventory_system } %>
<h1 class="text-light text-center">Add Product | Inventory System</h1>
<%= render partial: 'form', locals: { inventory_system: @inventory_system } %>
<%= render partial: 'footer', locals: { inventory_system: @inventory_system } %>

app/views/inventory_systems/show.html.erb
<%= render partial: 'header', locals: { inventory_system: @inventory_system } %>
<h1>| Product: <%= @inventory_system.product_name %> |</h1>
<%= render "show", inventory_system: @inventory_system %>

<%= render partial: 'footer', locals: { inventory_system: @inventory_system } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/my_project/example_project.html.erb
<h1>Hi, Project!</h1>

app/views/posts/edit.html.erb
<!--<!doctype html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--  <meta charset="UTF-8">-->
<!--  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">-->
<!--  <meta http-equiv="X-UA-Compatible" content="ie=edge">-->
<!--  <title>Document</title>-->
<!--</head>-->
<!--<body class="text-center pt-4 bg-dark">-->
<!--<div class="container py-2">-->
<!--  <h1 class="text-light text-center">Edit List</h1>-->

<!--  <table class="table border border-4 text-light">-->
<!--    <thead class="border border-4 bg-light">-->
<!--    <tr class="border border-4 border-light">-->
<!--      <td class="border border-2 border-light">Product Name</td>-->
<!--      <td class="border border-2 border-light">Product ID</td>-->
<!--      <td class="border border-2 border-light">Product Quantity</td>-->
<!--      <td class="border border-2 border-light">Product Description</td>-->
<!--      <td class="border border-2 border-light">Product Availability</td>-->

<!--    </tr>-->
<!--    </thead>-->
    <%# @posts.each do |post| %>
<!--      <tr class="border border-4 border-light">-->
<!--        <td class="border border-2 border-light"><%#= post.product_name %> </td>-->
<!--        <td class="border border-2 border-light"><%#= post.product_id %></td>-->
<!--        <td class="border border-2 border-light"><%#= post.product_quantity %></td>-->
<!--        <td class="border border-2 border-light"><%#= post.product_description %></td>-->
<!--        <td class="border border-2 border-light"><%#= post.product_availability %></td>-->
<!--      </tr>-->
    <%# end %>
<!--  </table>-->
<!--  <p><%#= link_to 'Back to Post', posts_new_path, class:'text-primary' %></p>-->

<!--</div>-->
<!--</body>-->
<!--</html>-->

app/views/posts/index.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body class="text-center pt-4 bg-dark">
<div class="container py-2">
  <h1 class="text-light text-center">Post List</h1>

  <table class="table border border-4 text-light">
    <thead class="border border-4 bg-light">
    <tr class="border border-4 border-light">
      <td class="border border-2 border-light">Product Name</td>
      <td class="border border-2 border-light">Product ID</td>
      <td class="border border-2 border-light">Product Quantity</td>
      <td class="border border-2 border-light">Product Description</td>
      <td class="border border-2 border-light">Product Availability</td>
    </tr>
    </thead>
    <% @posts.each do |post| %>
      <tr class="border border-4 border-light">
        <td class="border border-2 border-light"><%= post.product_name %> </td>
        <td class="border border-2 border-light"><%= post.product_id %></td>
        <td class="border border-2 border-light"><%= post.product_quantity %></td>
        <td class="border border-2 border-light"><%= post.product_description %></td>
        <td class="border border-2 border-light"><%= post.product_availability %></td>
      </tr>
    <% end %>
  </table>

  <p><%= link_to '', new_post_path, class:'text-primary' %></p>

</div>
</body>
</html>

app/views/posts/new.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body class="text-center pt-4 bg-dark">
  <div class="container">
    <div class="card">
      <div class="card-body card rounded-5">
    <h1 class="text-dark">New Post</h1>

    <%= form_with model: @post do |form| %>
      <div class="container">
        <div class="py-2">
          <label for=""><%= form.text_field :product_name, class: 'form-control-lg', placeholder: "Product Name" %></label>
        </div>
        <div class="py-2">
          <label for=""><%= form.number_field :product_id, class: 'form-control-lg', maxlength: 5, placeholder: "Product ID", required: true%></label>
        </div>
        <div class="py-2">
          <label><%= form.number_field :product_quantity, class:'form-control-lg',placeholder: "Product Quantity", required: true%></label>
        </div>
        <div class="py-2">
          <label><%= form.text_field :product_description, class:'form-control-lg',placeholder:"Product Description", required:true%></label>
        </div>
        <div class="py-2">
          <label><%= form.text_field :product_availability, class:'form-control-lg',placeholder:"Product Availability", required:true%></label>
        </div>
        <div class="py-2">
        <%= form.submit class: 'btn btn-lg mt-1'%>
        </div>
        <div>
          <p><%= link_to 'Back to Table Post',inventory_systems_path , class:'text-primary'%></p>
        </div>
      </div>
      </div>
      </div>
    <% end %>

</body>
</html>

app/views/posts/show.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <div class="container">
    <h1>show id: <%= @post.id %></h1>
    <ul>
      <li><%= @post.product_name %></li>
      <li><%= @post.product_id %></li>
    </ul>
  </div>
</body>
</html>

app/views/posts/update.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>

</body>
</html>

app/views/welcome/friday.html.erb
<h1>Tulog malala</h1>

app/views/welcome/index.html.erb
<p>Hola! It's <%= Time.now %></p>
<p><%= link_to 'Monday', welcome_say_monday_path %></p>
<p><%= link_to 'Tuesday', welcome_tuesday_path %></p>
<p><%= link_to 'Wednesday', welcome_wednesday_path %></p>
<p><%= link_to 'Thursday', welcome_thursday_path %></p>
<p><%= link_to 'Friday', welcome_friday_path %></p>

app/views/welcome/monday.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Login</title>
</head>
<body>
<header>
  <nav id="navbar">
    <div class="container">
      <h1 class="logo"><a href="index.html">MCVG</a></h1>
      <ul>
        <li><a class="current" href="index.html">Home</a></li>
        <li><a href="about.html">About</a></li>
        <li><a href="contact.html">Contact</a></li>
      </ul>
    </div>
  </nav>

  <div id="showcase">
    <div class="container">
      <div class="showcase-content">
        <h1><span class="text-primary">Hi,</span> Im Mark</h1>
        <p class="lead">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolor, eligendi laboriosam. Repellendus officia harum eaque.</p>
        <a class="btn" href="about.html">About My Self</a>
      </div>
    </div>
  </div>
</header>

<section id="home-info" class="bg-dark">
  <div class="info-img"></div>
  <div class="info-content">
    <h2><span class="text-primary">My</span> Life</h2>
    <p>
      Lorem ipsum dolor, sit amet consectetur adipisicing elit. Assumenda
      aliquam dolor alias iste autem, quaerat magni unde accusantium qui
      fuga placeat quidem quo pariatur, voluptatum, ea sequi? Corporis,
      explicabo quisquam dolor placeat praesentium nesciunt mollitia quos
      nobis natus voluptatum asperiores!
    </p>
    <a href="about.html" class="btn btn-light">Read More</a>
  </div>
</section>

<section id="features">
  <div class="box bg-light">
    <i class="fas fa-hotel fa-3x"></i>
    <h3>Great Location</h3>
    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ut, omnis?</p>
  </div>
  <div class="box bg-primary">
    <i class="fas fa-utensils fa-3x"></i>
    <h3>Free Meals</h3>
    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ut, omnis?</p>
  </div>
  <div class="box bg-light">
    <i class="fas fa-dumbbell fa-3x"></i>
    <h3>Fitness Room</h3>
    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ut, omnis?</p>
  </div>
</section>

<div class="clr"></div>

<footer id="main-footer">
  <p>MCVG &copy; 2022, All Rights Reserved</p>
</footer>
<p><%= link_to 'Back to Index', welcome_index_path %></p>
</body>
</html>

app/views/welcome/thursday.html.erb
<h1>mahabang tulog</h1>

app/views/welcome/tueday.html.erb
<h1>sobrang pag aaral</h1>

app/views/welcome/wednesday.html.erb
<h1>aral</h1>